GET  http://localhost:3000/api/detailPesanans/4 HTTP/1.1
Content-Type: application/

GET  http://localhost:3000/api/detailPesanans HTTP/1.1
Content-Type: application/json

POST http://localhost:3000/api/detailPesanans HTTP/1.1
Content-Type: application/json

{  
  "pesanan_id": 11,
  "produk_id": 1,
  "jumlah_produk": 3,
  "harga_produk_pembelian": 500000
}

PUT  http://localhost:3000/api/detailPesanans/4 HTTP/1.1
Content-Type: application/json

{  
  "pesanan_id": 11,
  "produk_id": 1,
  "jumlah_produk": 3,
  "harga_produk_pembelian": 400000
}

GET  http://localhost:3000/api/keranjangs HTTP/1.1
Content-Type: application/json

GET  http://localhost:3000/api/keranjangs/2 HTTP/1.1
Content-Type: application/json

DELETE http://localhost:3000/api/keranjangs/2 HTTP/1.1
Content-Type: application/json

PUT http://localhost:3000/api/keranjangs/2 HTTP/1.1
Content-Type: application/json

{  
  "user_id": 1,
  "produk_id": 1,
  "jumlah_produk": 10,
  "tanggal_penambahan": "06-09-2007"
}

POST http://localhost:3000/api/keranjangs HTTP/1.1
Content-Type: application/json

{  
  "user_id": 1,
  "produk_id": 1,
  "jumlah_produk": 3,
  "tanggal_penambahan": "05-09-2007"
}


GET  http://localhost:3000/api/pesanans HTTP/1.1
Content-Type: application/json

GET  http://localhost:3000/api/pesanans/12 HTTP/1.1
Content-Type: application/json

PUT http://localhost:3000/api/pesanans/12 HTTP/1.1
Content-Type: application/json

{
  "user_id": 1,
  "total_harga": 500000,
  "status": "CANCELLED",
  "tanggal_pesanan": "05-09-2007"
}

DELETE  http://localhost:3000/api/pesanans/12 HTTP/1.1
Content-Type: application/json

POST http://localhost:3000/api/pesanans HTTP/1.1
Content-Type: application/json

{
  "user_id": 1,
  "total_harga": 500000,
  "status": "PENDING",
  "tanggal_pesanan": "04-09-2007"
}

POST http://localhost:3000/api/produks HTTP/1.1
Content-Type: application/json

{
  "name": "Infinix Hot 40 PRO",
  "deskripsi": "Hp terbaru dari bran infinix dengan spesifikasi yang bagus",
  "harga": 1500000,
  "jumlah_stok": 20,
  "tanggal_masuk": "02-09-2006"
}

GET  http://localhost:3000/api/produks HTTP/1.1
Content-Type: application/json

GET  http://localhost:3000/api/produks/2 HTTP/1.1
Content-Type: application/json

PUT  http://localhost:3000/api/produks/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Infinix Hot 40 PRO",
  "deskripsi": "Hp terbaru dari bran infinix dengan spesifikasi yang bagus",
  "harga": 2000000,
  "jumlah_stok": 20,
  "tanggal_masuk": "02-03-2006"
}

DELETE http://localhost:3000/api/produks/4 HTTP/1.1
Content-Type: application/json

POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@gmail.com",
  "password": "password123",
  "pengguna": "PENGGUNA",
  "tanggal_buat_akun": "16-12-2024"
}

POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "john.doe@gmail.com",
  "password": "password123"
}